module.exports = {
  apps: [
    {
        name: "main_api",
        script: "app.js",
        watch: false,
        merge_logs: true,
        wait_ready: true,
        pid_file: "./pids/main_api.pid",
        out_file: "./logs/main_api.log",
        error_file: "./errors/main_api.log",
        log_date_format: "YYYY-MM-DD HH:mm:ss SSS",
        // cwd: "/home/apexzonedemo/taxiapp/snapbackend",
    },
      {
          name: "admin_socket",
          script: "admin_socket.js",
          watch: false,
          merge_logs: true,
          wait_ready: true,
          // cwd: "/home/apexzonedemo/taxiapp/snapbackend",
          pid_file: "./pids/admin_socket.pid",
          out_file: "./logs/admin_socket.log",
          error_file: "./errors/admin_socket.log",
          log_date_format: "YYYY-MM-DD HH:mm:ss SSS",
      },
      {
          name: "driver_socket",
          script: "driver_socket.js",
          watch: false,
          merge_logs: true,
          wait_ready: true,
          // cwd: "/home/apexzonedemo/taxiapp/snapbackend",
          pid_file: "./pids/driver_socket.pid",
          out_file: "./logs/driver_socket.log",
          error_file: "./errors/driver_socket.log",
          log_date_format: "YYYY-MM-DD HH:mm:ss SSS",
      },
      {
          name: "passenger_socket",
          script: "passenger_socket.js",
          watch: false,
          merge_logs: true,
          wait_ready: true,
          // cwd: "/home/apexzonedemo/taxiapp/snapbackend",
          pid_file: "./pids/passenger_socket.pid",
          out_file: "./logs/passenger_socket.log",
          error_file: "./errors/passenger_socket.log",
          log_date_format: "YYYY-MM-DD HH:mm:ss SSS",
      },
  ],
};
